title: SG Eco Office
url: "https://www.sgeco.gov.sg" # the base hostname & protocol for your site, e.g. http://sgeco.gov.sg
favicon: /images/favicon.ico

# Site colors
# 265433
colors:
  primary-color: '#265433'
  secondary-color: '#265433'
  media-colors:
    - title: media-color-one
      color: '#265433'
    - title: media-color-two
      color: '#265433'
    - title: media-color-three
      color: '#265433'
    - title: media-color-four
      color: '#265433'
    - title: media-color-five
      color: '#265433'


google_analytics: UA-183999332-3
resources_name: news

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: test test

staging: https://mewr-eco-staging.netlify.app
prod: https://mewr-eco-prod.netify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
