title: SG Eco Office
url: "" # the base hostname & protocol for your site, e.g. http://sgeco.gov.sg
favicon: /images/favicon-isomer.ico

# Site colors
# #009459
colors:
  primary-color: '#009459'
  secondary-color: '#009459'
  media-colors:
    - title: media-color-one
      color: '#DC3646'
    - title: media-color-two
      color: '#DC3646'
    - title: media-color-three
      color: '#DC3646'
    - title: media-color-four
      color: '#DC3646'
    - title: media-color-five
      color: '#DC3646'


collections:
  apply:
    output: true
  showcase:
    output: true
resources_name: news

##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test

